spring.application.name=payment-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/payment_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Kafka bootstrap ---
spring.kafka.bootstrap-servers=localhost:9092

# --- Consumer (payment-service consumes OrderCreatedEvent) ---
spring.kafka.consumer.group-id=payment-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Tell Spring which packages are trusted for JSON deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=com.ecart.order.events

# Set the default type for the consumer value (OrderCreatedEvent)
spring.kafka.consumer.properties.spring.json.value.default.type=com.ecart.order.events.OrderCreatedEvent

# --- Producer (payment-service produces PaymentResultEvent) ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# --- Topics (custom props you will use in code) ---
topics.order-created=order.created
topics.payment-result=payment.result